version: '3.8'
services:
  store:
    image: redis:alpine
    restart: always
    networks:
      - network_1
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 3
      start_period: 10s

  server:
    networks:
      - network_1
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      store:
        condition: service_healthy

networks:
  network_1:
